export const CSS = `
@keyframes fadeIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}
@keyframes slideUp{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}
@keyframes pulse{0%,100%{opacity:.6}50%{opacity:1}}
*{box-sizing:border-box}body{margin:0;padding:0;background:#101314}button{font-family:inherit}
`;

export const S = {
  app: { minHeight: '100vh', background: 'linear-gradient(180deg,#f7f9fb,#eef2f5 46%,#f8fafc)', color: '#172026', fontFamily: 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif', paddingBottom: 40 },
  onboardingWrap: { minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20 },
  onboardingCard: { width: '100%', maxWidth: 720, background: '#ffffff', border: '1px solid #e5eaf0', borderRadius: 8, padding: 22, boxShadow: '0 24px 70px rgba(15,23,32,.14)' },
  onboardingText: { margin: '0 0 18px', color: '#64727d', lineHeight: 1.5, fontSize: 14 },
  loadScreen: { minHeight: '100vh', background: '#f7f9fb', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  loadText: { color: '#00a676', letterSpacing: '.4em', fontSize: 12, animation: 'pulse 1.5s infinite' },
  header: { padding: '20px 20px 16px', background: 'rgba(255,255,255,.92)', borderBottom: '1px solid #e5eaf0', boxShadow: '0 14px 40px rgba(15,23,32,.08)', backdropFilter: 'blur(18px)' },
  brandRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 },
  logo: { display: 'flex', alignItems: 'center', gap: 12 },
  logoMark: { width: 40, height: 40, borderRadius: 8, background: 'linear-gradient(135deg,#00a676,#20c997)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#ffffff', fontSize: 18, boxShadow: '0 10px 26px rgba(0,166,118,.28)' },
  brandName: { fontSize: 17, fontWeight: 850, letterSpacing: '.04em', color: '#172026' },
  brandSub: { fontSize: 11, letterSpacing: '.08em', color: '#64727d', marginTop: 2 },
  iconBtn: { background: '#ffffff', border: '1px solid #e5eaf0', color: '#64727d', padding: 8, borderRadius: 8, cursor: 'pointer', display: 'flex', boxShadow: '0 8px 22px rgba(15,23,32,.08)' },
  seasonBar: { background: '#f7f9fb', border: '1px solid #e5eaf0', padding: '10px 12px', borderRadius: 8, marginBottom: 12, display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  seasonLabel: { fontSize: 10, letterSpacing: '.14em', color: '#64727d', fontFamily: 'system-ui,sans-serif', fontWeight: 800 },
  seasonDate: { fontSize: 10, color: '#64727d', marginTop: 3, fontFamily: 'system-ui,sans-serif', fontWeight: 700 },
  seasonPhase: { fontSize: 10, letterSpacing: '.1em', color: '#00a676', fontFamily: 'system-ui,sans-serif', fontWeight: 800 },
  todayCard: { background: '#ffffff', border: '1px solid #e5eaf0', borderRadius: 8, padding: 14, boxShadow: '0 14px 34px rgba(15,23,32,.08)' },
  todayTitle: { fontSize: 10, letterSpacing: '.18em', color: '#64727d', fontFamily: 'system-ui,sans-serif', fontWeight: 850, marginBottom: 8 },
  todayRow: { display: 'flex', justifyContent: 'space-between', gap: 10, padding: '8px 0', borderBottom: '1px solid #eef2f5', fontSize: 12, fontFamily: 'system-ui,sans-serif' },
  todayRowLast: { display: 'flex', justifyContent: 'space-between', gap: 10, padding: '8px 0', fontSize: 12, fontFamily: 'system-ui,sans-serif' },
  statsGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 },
  statCard: { background: '#ffffff', border: '1px solid #e5eaf0', padding: '12px 12px', borderRadius: 8, boxShadow: '0 10px 28px rgba(15,23,32,.07)' },
  statLabel: { fontSize: 9, letterSpacing: '.2em', display: 'flex', alignItems: 'center', gap: 6, marginBottom: 4, fontFamily: 'system-ui,sans-serif' },
  statValue: { fontSize: 19, fontWeight: 850, color: '#172026' },
  nav: { display: 'flex', borderTop: '1px solid #e5eaf0', background: 'rgba(255,255,255,.94)', position: 'fixed', bottom: 0, left: 0, right: 0, zIndex: 10, backdropFilter: 'blur(16px)', boxShadow: '0 -12px 34px rgba(15,23,32,.08)' },
  navBtn: { flex: 1, background: 'transparent', border: 'none', padding: '9px 4px 10px', fontSize: 9, letterSpacing: '.03em', textTransform: 'uppercase', cursor: 'pointer', fontFamily: 'system-ui,sans-serif', fontWeight: 800, transition: 'color .2s', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 3, minWidth: 0 },
  main: { animation: 'fadeIn .3s ease-out' },
  vp: { padding: '24px 20px 92px', maxWidth: 920, margin: '0 auto' },
  et: { marginBottom: 20 },
  el: { fontSize: 10, letterSpacing: '.22em', color: '#00a676', fontFamily: 'system-ui,sans-serif', fontWeight: 850, marginBottom: 8 },
  eh: { fontSize: 34, fontWeight: 900, margin: 0, lineHeight: 1.05, color: '#172026', letterSpacing: '-.02em' },
  sumCard: { background: '#ffffff', border: '1px solid #e5eaf0', borderRadius: 8, padding: 16, marginBottom: 16, boxShadow: '0 14px 34px rgba(15,23,32,.08)' },
  kpiGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 16 },
  kpiCard: { background: '#ffffff', border: '1px solid #e5eaf0', borderRadius: 8, padding: 16, boxShadow: '0 14px 34px rgba(15,23,32,.08)' },
  kpiLabel: { fontSize: 10, color: '#64727d', letterSpacing: '.12em', textTransform: 'uppercase', fontFamily: 'system-ui,sans-serif', marginBottom: 8, fontWeight: 800 },
  kpiValue: { fontSize: 25, color: '#172026', fontWeight: 900, lineHeight: 1 },
  profileHero: { display: 'flex', alignItems: 'center', gap: 14, background: '#ffffff', border: '1px solid #e5eaf0', borderRadius: 8, padding: 16, marginBottom: 16, boxShadow: '0 14px 34px rgba(15,23,32,.08)' },
  profileSub: { color: '#64727d', fontSize: 13, fontWeight: 650, marginTop: 4 },
  segmentGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8, marginBottom: 16 },
  segmentCard: { background: '#ffffff', border: '1px solid #e5eaf0', borderRadius: 8, padding: 12, boxShadow: '0 10px 26px rgba(15,23,32,.06)' },
  segmentHead: { display: 'flex', justifyContent: 'space-between', fontSize: 11, color: '#64727d', fontFamily: 'system-ui,sans-serif', marginBottom: 6, fontWeight: 750 },
  sumRow: { display: 'flex', justifyContent: 'space-between', padding: '9px 0', borderBottom: '1px solid #eef2f5', fontSize: 13 },
  sumK: { color: '#64727d', fontFamily: 'system-ui,sans-serif', fontSize: 12 },
  sumV: { fontWeight: 700 },
  primaryBtn: { width: '100%', background: 'linear-gradient(135deg,#172026,#2c3a42)', color: '#ffffff', border: 'none', padding: 16, borderRadius: 8, fontSize: 13, fontWeight: 900, letterSpacing: '.1em', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 10, fontFamily: 'system-ui,sans-serif', marginBottom: 16, boxShadow: '0 18px 38px rgba(15,23,32,.18)' },
  secBtn: { width: '100%', background: '#ffffff', color: '#172026', border: '1px solid #d6dde3', padding: 12, borderRadius: 8, fontSize: 11, fontWeight: 850, letterSpacing: '.1em', cursor: 'pointer', fontFamily: 'system-ui,sans-serif', marginBottom: 16, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, boxShadow: '0 12px 28px rgba(15,23,32,.07)' },
  objCard: { background: '#ffffff', border: '1px solid #e5eaf0', borderRadius: 8, padding: 16, marginBottom: 16, boxShadow: '0 14px 34px rgba(15,23,32,.08)' },
  secTitle: { fontSize: 10, letterSpacing: '.18em', color: '#64727d', display: 'flex', alignItems: 'center', gap: 6, marginBottom: 10, fontFamily: 'system-ui,sans-serif', fontWeight: 850 },
  objRow: { marginBottom: 10 },
  objLabel: { fontSize: 12, color: '#172026', marginBottom: 4, fontFamily: 'system-ui,sans-serif', fontWeight: 650 },
  progBar: { width: '100%', height: 5, background: '#e7edf1', borderRadius: 8, overflow: 'hidden' },
  progFill: { height: '100%', background: '#00a676', transition: 'width .3s' },
  objReward: { fontSize: 10, color: '#00a676', textAlign: 'right', marginTop: 4, fontFamily: 'system-ui,sans-serif', fontWeight: 800 },
  quickActs: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 16 },
  quickCard: { background: '#ffffff', border: '1px solid #e5eaf0', borderRadius: 8, padding: '14px 12px', cursor: 'pointer', textAlign: 'left', color: '#172026', fontFamily: 'inherit', boxShadow: '0 14px 34px rgba(15,23,32,.08)' },
  qLabel: { fontSize: 14, fontWeight: 700, marginTop: 8 },
  qSub: { fontSize: 10, color: '#64727d', marginTop: 2, fontFamily: 'system-ui,sans-serif' },
  histCard: { background: '#ffffff', border: '1px solid #e5eaf0', borderRadius: 8, padding: 16, boxShadow: '0 14px 34px rgba(15,23,32,.08)' },
  promiseCard: { background: '#fffdf7', border: '1px solid #e8dfc8', borderRadius: 8, padding: 16, marginBottom: 16, boxShadow: '0 14px 34px rgba(15,23,32,.06)' },
  promiseRow: { display: 'flex', justifyContent: 'space-between', gap: 10, color: '#172026', fontSize: 12, fontFamily: 'system-ui,sans-serif', padding: '7px 0', borderBottom: '1px solid #f0e8d7' },
  fixtureRow: { background: '#f7f9fb', border: '1px solid #e5eaf0', borderRadius: 8, padding: 12, marginBottom: 8, color: '#172026', fontSize: 13, fontFamily: 'system-ui,sans-serif' },
  fixtureMeta: { color: '#64727d', fontSize: 11, marginTop: 4 },
  calendarLegend: { fontSize: 12, color: '#3f5663', fontFamily: 'system-ui,sans-serif', marginTop: 8 },
  preAccordBadge: { display: 'inline-flex', alignItems: 'center', padding: '3px 8px', borderRadius: 8, background: '#fff4d6', color: '#8a6f1f', fontSize: 9, fontWeight: 850, letterSpacing: '.08em', fontFamily: 'system-ui,sans-serif' },
  linkBtn: { background: 'transparent', border: 'none', color: '#172026', padding: 0, fontWeight: 900, cursor: 'pointer', fontFamily: 'inherit', fontSize: 'inherit', textAlign: 'left' },
  tableRow: { display: 'grid', gridTemplateColumns: '1fr 54px 48px 34px 36px', gap: 6, alignItems: 'center', background: '#f7f9fb', border: '1px solid #e5eaf0', borderRadius: 8, padding: '10px 9px', marginBottom: 6, color: '#172026', fontSize: 11, fontFamily: 'system-ui,sans-serif' },
  statLineGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8, marginBottom: 8 },
  scoutCard: { background: '#f7f9fb', border: '1px solid #e5eaf0', borderRadius: 8, padding: 10, marginTop: 8 },
  suggestionCard: { background: '#f3fbf8', border: '1px solid #cfeee3', borderRadius: 8, padding: 16, marginBottom: 16, boxShadow: '0 14px 34px rgba(15,23,32,.06)' },
  suggestionRow: { color: '#246555', fontSize: 12, fontFamily: 'system-ui,sans-serif', lineHeight: 1.45, padding: '6px 0' },
  decisionCard: { background: '#ffffff', border: '1px solid #e5eaf0', borderRadius: 8, padding: 16, marginBottom: 16, boxShadow: '0 14px 34px rgba(15,23,32,.08)' },
  decisionRow: { width: '100%', background: '#f7f9fb', border: '1px solid #e5eaf0', borderRadius: 8, padding: '10px 12px', display: 'flex', justifyContent: 'space-between', gap: 10, color: '#172026', cursor: 'pointer', marginBottom: 8, fontSize: 12, fontWeight: 750 },
  offerRow: { background: '#f7f9fb', border: '1px solid #dce8ff', borderRadius: 8, padding: 12, display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'center', marginBottom: 8 },
  offerMeta: { color: '#64727d', fontSize: 11, marginTop: 4, fontFamily: 'system-ui,sans-serif' },
  offerActions: { display: 'flex', gap: 6, flexShrink: 0 },
  miniPrimary: { background: '#172026', color: '#ffffff', border: 'none', borderRadius: 8, padding: '8px 9px', fontSize: 10, fontWeight: 850, cursor: 'pointer' },
  miniGhost: { background: '#ffffff', color: '#64727d', border: '1px solid #d6dde3', borderRadius: 8, padding: '8px 9px', fontSize: 10, fontWeight: 850, cursor: 'pointer' },
  histRow: { display: 'flex', justifyContent: 'space-between', padding: '6px 0', fontSize: 13, borderBottom: '1px solid #eef2f5' },
  histWeek: { color: '#64727d', fontFamily: 'system-ui,sans-serif', fontSize: 11 },
  histNet: { fontWeight: 700 },
  histRep: { color: '#64727d', fontSize: 11, fontFamily: 'system-ui,sans-serif' },
  cardList: { display: 'flex', flexDirection: 'column', gap: 10 },
  pCard: { background: '#ffffff', border: '1px solid #e5eaf0', borderRadius: 8, padding: 14, animation: 'slideUp .3s ease-out', boxShadow: '0 14px 34px rgba(15,23,32,.08)' },
  pTop: { display: 'flex', gap: 12, marginBottom: 10 },
  badge: { width: 56, height: 56, borderRadius: 8, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', color: '#ffffff', flexShrink: 0, boxShadow: '0 12px 24px rgba(15,23,32,.14)' },
  playerAvatar: { width: 42, height: 42, borderRadius: 8, background: '#f0f5f7', color: '#172026', border: '1px solid #e5eaf0', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 13, fontWeight: 900, flexShrink: 0 },
  badgeNum: { fontSize: 22, fontWeight: 900, lineHeight: 1 },
  badgePos: { fontSize: 9, letterSpacing: '.1em', fontWeight: 700, marginTop: 2, fontFamily: 'system-ui,sans-serif' },
  pInfo: { flex: 1, minWidth: 0 },
  pName: { fontSize: 15, color: '#172026', marginBottom: 2, fontWeight: 700 },
  pMeta: { fontSize: 11, color: '#64727d', fontFamily: 'system-ui,sans-serif', marginBottom: 4 },
  pMeta2: { fontSize: 10, color: '#64727d', fontFamily: 'system-ui,sans-serif', marginTop: 4, display: 'flex', gap: 5, flexWrap: 'wrap' },
  pStats: { fontSize: 11, color: '#3f5663', fontFamily: 'system-ui,sans-serif', display: 'flex', gap: 6, flexWrap: 'wrap', fontWeight: 700 },
  meterRow: { display: 'grid', gridTemplateColumns: '64px 1fr 28px', gap: 7, alignItems: 'center', marginTop: 5, fontSize: 10, color: '#64727d', fontFamily: 'system-ui,sans-serif' },
  injTag: { fontSize: 10, color: '#b42318', fontFamily: 'system-ui,sans-serif', marginTop: 4, fontWeight: 600 },
  signBtn: { width: '100%', background: '#172026', color: '#ffffff', border: 'none', padding: 11, borderRadius: 8, fontSize: 11, fontWeight: 900, letterSpacing: '.1em', fontFamily: 'system-ui,sans-serif', display: 'flex', justifyContent: 'space-between', alignItems: 'center', boxShadow: '0 12px 24px rgba(15,23,32,.18)' },
  rActions: { display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 4 },
  actBtn: { background: '#f7f9fb', color: '#172026', border: '1px solid #d6dde3', padding: '8px 4px', borderRadius: 8, fontSize: 9, fontWeight: 800, letterSpacing: '.08em', cursor: 'pointer', fontFamily: 'system-ui,sans-serif', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 3 },
  relBtn: { background: '#fff6f6', color: '#b42318', border: '1px solid #f3c7c2', padding: '8px 4px', borderRadius: 8, fontSize: 9, fontWeight: 800, letterSpacing: '.08em', cursor: 'pointer', fontFamily: 'system-ui,sans-serif', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 3 },
  empty: { textAlign: 'center', color: '#64727d', padding: '60px 20px', fontSize: 14, fontStyle: 'italic', lineHeight: 1.6 },
  emptySmall: { color: '#64727d', padding: '12px 0', fontSize: 12, fontFamily: 'system-ui,sans-serif' },
  filterPanel: { background: '#ffffff', border: '1px solid #e5eaf0', borderRadius: 8, padding: 16, marginBottom: 16, boxShadow: '0 14px 34px rgba(15,23,32,.08)' },
  favoriteBtn: { position: 'absolute', right: 12, top: 12, zIndex: 2, width: 34, height: 34, borderRadius: 8, border: '1px solid #e5eaf0', background: '#ffffff', color: '#00a676', fontSize: 18, fontWeight: 900, boxShadow: '0 8px 18px rgba(15,23,32,.12)', cursor: 'pointer' },
  freeTag: { position: 'absolute', left: 12, top: 12, zIndex: 2, background: '#172026', color: '#ffffff', borderRadius: 8, padding: '6px 8px', fontSize: 9, fontWeight: 900, letterSpacing: '.08em', fontFamily: 'system-ui,sans-serif' },
  offCard: { background: '#ffffff', border: '1px solid #e5eaf0', borderRadius: 8, padding: 16, boxShadow: '0 14px 34px rgba(15,23,32,.08)' },
  offHead: { display: 'flex', alignItems: 'center', gap: 12, marginBottom: 10 },
  offLabel: { fontSize: 15, fontWeight: 850, color: '#172026' },
  offDesc: { fontSize: 11, color: '#64727d', fontFamily: 'system-ui,sans-serif', marginTop: 2 },
  offLvl: { display: 'flex', gap: 4 },
  lvlDot: { width: 10, height: 10, borderRadius: 8 },
  agencyAvatar: { width: 44, height: 44, borderRadius: 8, color: '#ffffff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 13, fontWeight: 900, fontFamily: 'system-ui,sans-serif', boxShadow: '0 10px 24px rgba(15,23,32,.14)' },
  formGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 12 },
  fieldLabel: { color: '#64727d', display: 'flex', flexDirection: 'column', gap: 5, fontSize: 10, letterSpacing: '.1em', textTransform: 'uppercase', fontFamily: 'system-ui,sans-serif', fontWeight: 850 },
  textInput: { width: '100%', background: '#f7f9fb', border: '1px solid #d6dde3', color: '#172026', borderRadius: 8, padding: '10px 9px', fontSize: 13, fontFamily: 'system-ui,sans-serif', outline: 'none' },
  colorInput: { width: '100%', height: 39, background: '#f7f9fb', border: '1px solid #d6dde3', borderRadius: 8, padding: 4, cursor: 'pointer' },
  staffGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 },
  staffItem: { background: '#f7f9fb', border: '1px solid #e5eaf0', borderRadius: 8, padding: 10 },
  staffTop: { display: 'flex', justifyContent: 'space-between', gap: 8, color: '#172026', fontSize: 12, fontFamily: 'system-ui,sans-serif', marginBottom: 6 },
  staffBtn: { width: '100%', marginTop: 9, background: '#00a676', color: '#ffffff', border: 'none', padding: 9, borderRadius: 8, fontSize: 10, fontWeight: 900, letterSpacing: '.1em', cursor: 'pointer', fontFamily: 'system-ui,sans-serif', boxShadow: '0 12px 24px rgba(0,166,118,.22)' },
  upBtn: { width: '100%', background: '#172026', color: '#ffffff', border: 'none', padding: 11, borderRadius: 8, fontSize: 11, fontWeight: 900, letterSpacing: '.1em', cursor: 'pointer', fontFamily: 'system-ui,sans-serif', boxShadow: '0 12px 24px rgba(15,23,32,.16)' },
  maxLvl: { textAlign: 'center', color: '#00a676', fontSize: 10, letterSpacing: '.14em', fontFamily: 'system-ui,sans-serif', fontWeight: 850, padding: 10 },
  feedCard: { background: '#ffffff', border: '1px solid #e5eaf0', borderRadius: 8, padding: 16, boxShadow: '0 14px 34px rgba(15,23,32,.08)' },
  feedHead: { display: 'flex', alignItems: 'center', gap: 10, marginBottom: 10 },
  newsIcon: { width: 38, height: 38, borderRadius: 8, color: '#ffffff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 12, fontWeight: 900, boxShadow: '0 10px 22px rgba(15,23,32,.16)' },
  feedType: { fontSize: 9, letterSpacing: '.16em', textTransform: 'uppercase', color: '#00a676', fontFamily: 'system-ui,sans-serif', marginBottom: 6, fontWeight: 850 },
  feedAccount: { display: 'flex', justifyContent: 'space-between', gap: 8, fontSize: 11, color: '#3f5663', fontFamily: 'system-ui,sans-serif', marginBottom: 8 },
  feedText: { fontSize: 14, color: '#172026', lineHeight: 1.45, marginBottom: 8, fontWeight: 600 },
  feedMeta: { display: 'flex', justifyContent: 'space-between', gap: 8, fontSize: 11, color: '#64727d', fontFamily: 'system-ui,sans-serif' },
  newsReactions: { display: 'flex', gap: 10, marginTop: 10, paddingTop: 10, borderTop: '1px solid #eef2f5', color: '#64727d', fontSize: 11, fontFamily: 'system-ui,sans-serif' },
  msgCard: { background: '#ffffff', border: '1px solid #e5eaf0', borderRadius: 8, padding: 16, boxShadow: '0 14px 34px rgba(15,23,32,.08)' },
  msgSubject: { fontSize: 15, color: '#172026', fontWeight: 850, marginBottom: 4 },
  msgFrom: { fontSize: 11, color: '#00a676', fontFamily: 'system-ui,sans-serif', marginBottom: 8, fontWeight: 800 },
  msgBody: { fontSize: 13, color: '#3f5663', lineHeight: 1.5, fontFamily: 'system-ui,sans-serif', marginBottom: 12 },
  msgHint: { fontSize: 11, color: '#246555', lineHeight: 1.4, fontFamily: 'system-ui,sans-serif', marginBottom: 10, background: '#f3fbf8', border: '1px solid #cfeee3', borderRadius: 8, padding: 8 },
  msgActions: { display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 6 },
  msgBtn: { background: '#f7f9fb', border: '1px solid #d6dde3', borderRadius: 8, color: '#172026', padding: 9, cursor: 'pointer', fontSize: 10, fontWeight: 850, fontFamily: 'system-ui,sans-serif' },
  resolved: { color: '#00a676', fontSize: 12, fontFamily: 'system-ui,sans-serif', fontWeight: 750, whiteSpace: 'pre-line', lineHeight: 1.45, background: '#f3fbf8', border: '1px solid #cfeee3', borderRadius: 8, padding: 10 },
  filterChips: { display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: 14 },
  chipBtn: { border: '1px solid #d6dde3', borderRadius: 8, padding: '8px 10px', fontSize: 10, fontWeight: 850, cursor: 'pointer', fontFamily: 'system-ui,sans-serif' },
  messagesLayout: { display: 'grid', gridTemplateColumns: '280px minmax(0, 1fr)', gap: 12, alignItems: 'start' },
  threadListPane: { display: 'flex', flexDirection: 'column', gap: 10 },
  threadContact: { width: '100%', textAlign: 'left', background: '#ffffff', border: '1px solid #e5eaf0', borderRadius: 8, padding: 12, cursor: 'pointer', boxShadow: '0 10px 24px rgba(15,23,32,.06)' },
  threadContactTop: { display: 'flex', alignItems: 'center', gap: 10, minWidth: 0 },
  threadContactIcon: { width: 32, height: 32, borderRadius: 8, background: '#f3fbf8', color: '#00a676', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  threadContactTitle: { fontSize: 14, color: '#172026', fontWeight: 900, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  threadContactSub: { fontSize: 11, color: '#64727d', fontFamily: 'system-ui,sans-serif', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  threadContactMeta: { fontSize: 11, color: '#3f5663', fontFamily: 'system-ui,sans-serif', marginTop: 8, lineHeight: 1.4 },
  threadBadge: { minWidth: 20, height: 20, borderRadius: 10, background: '#b42318', color: '#ffffff', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', fontSize: 10, fontWeight: 900, flexShrink: 0 },
  threadPane: { background: '#ffffff', border: '1px solid #e5eaf0', borderRadius: 8, padding: 14, boxShadow: '0 14px 34px rgba(15,23,32,.08)', minWidth: 0, width: '100%' },
  chatHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 10, paddingBottom: 12, borderBottom: '1px solid #eef2f5', marginBottom: 12 },
  backBtn: { background: 'transparent', border: 'none', color: '#00a676', display: 'inline-flex', alignItems: 'center', gap: 4, padding: 0, marginBottom: 10, fontSize: 11, fontWeight: 900, cursor: 'pointer', fontFamily: 'system-ui,sans-serif' },
  chatTitle: { fontSize: 18, fontWeight: 900, color: '#172026' },
  chatSub: { fontSize: 11, color: '#64727d', fontFamily: 'system-ui,sans-serif', marginTop: 4 },
  chatTag: { fontSize: 9, letterSpacing: '.16em', textTransform: 'uppercase', color: '#00a676', fontFamily: 'system-ui,sans-serif', fontWeight: 900, background: '#f3fbf8', border: '1px solid #cfeee3', borderRadius: 8, padding: '6px 8px' },
  chatTimeline: { display: 'flex', flexDirection: 'column', gap: 14 },
  chatBlock: { display: 'flex', flexDirection: 'column', gap: 8 },
  chatBubbleLeft: { alignSelf: 'flex-start', background: '#f7f9fb', border: '1px solid #e5eaf0', borderRadius: 8, padding: 12, maxWidth: '88%', boxShadow: '0 8px 18px rgba(15,23,32,.04)' },
  chatBubbleRight: { alignSelf: 'flex-end', background: '#f3fbf8', border: '1px solid #cfeee3', borderRadius: 8, padding: 12, maxWidth: '88%', color: '#246555', fontSize: 12, lineHeight: 1.45, whiteSpace: 'pre-line', boxShadow: '0 8px 18px rgba(15,23,32,.04)' },
  chatMeta: { fontSize: 10, color: '#64727d', fontFamily: 'system-ui,sans-serif', marginBottom: 4, fontWeight: 800, textTransform: 'uppercase', letterSpacing: '.04em' },
  chatSubject: { fontSize: 13, color: '#172026', fontWeight: 850, marginBottom: 6 },
  chatBody: { fontSize: 13, color: '#3f5663', lineHeight: 1.55, fontFamily: 'system-ui,sans-serif' },
  chatEmpty: { minHeight: 280, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 10, color: '#64727d', textAlign: 'center' },
  chatEmptyTitle: { fontSize: 16, fontWeight: 900, color: '#172026' },
  chatEmptySub: { fontSize: 12, lineHeight: 1.5, maxWidth: 320, fontFamily: 'system-ui,sans-serif' },
  loadOlderBtn: { width: '100%', marginTop: 12, background: '#f7f9fb', border: '1px solid #d6dde3', borderRadius: 8, padding: '10px 12px', color: '#172026', fontSize: 11, fontWeight: 850, cursor: 'pointer', fontFamily: 'system-ui,sans-serif' },
  thread: { display: 'flex', flexDirection: 'column', gap: 10 },
  threadBlock: { display: 'flex', flexDirection: 'column', gap: 8 },
  threadMeta: { fontSize: 10, color: '#64727d', marginBottom: 6, fontWeight: 800, letterSpacing: '.04em', textTransform: 'uppercase' },
  incomingBubble: { background: '#f7f9fb', border: '1px solid #e5eaf0', borderRadius: 8, padding: 10, color: '#24313a', fontSize: 13, lineHeight: 1.45 },
  outgoingBubble: { background: '#f3fbf8', border: '1px solid #cfeee3', borderRadius: 8, padding: 10, color: '#246555', fontSize: 12, lineHeight: 1.45, whiteSpace: 'pre-line' },
  tabRow: { display: 'flex', gap: 8, marginBottom: 12, flexWrap: 'wrap' },
  tabBtn: { border: '1px solid #d6dde3', borderRadius: 8, padding: '8px 10px', fontSize: 10, fontWeight: 850, cursor: 'pointer', fontFamily: 'system-ui,sans-serif' },
  overlay: { position: 'fixed', inset: 0, background: 'rgba(0,0,0,.85)', zIndex: 100, display: 'flex', alignItems: 'flex-end', animation: 'fadeIn .2s ease-out' },
  modal: { width: '100%', maxHeight: '92vh', background: '#ffffff', borderTop: '2px solid #00a676', borderRadius: '8px 8px 0 0', overflow: 'hidden', display: 'flex', flexDirection: 'column', animation: 'slideUp .3s ease-out' },
  mHead: { display: 'flex', alignItems: 'center', gap: 8, padding: '14px 20px', borderBottom: '1px solid #e5eaf0', fontSize: 10, letterSpacing: '.18em', color: '#00a676', fontFamily: 'system-ui,sans-serif', fontWeight: 850, background: '#f7f9fb' },
  mClose: { marginLeft: 'auto', background: 'transparent', border: 'none', color: '#6a6660', cursor: 'pointer', padding: 4, display: 'flex' },
  mBody: { padding: 20, overflowY: 'auto', flex: 1 },
  mTitle: { fontSize: 22, fontWeight: 900, color: '#172026', margin: '0 0 4px', lineHeight: 1.2 },
  mText: { fontSize: 14, color: '#3f5663', lineHeight: 1.6, marginBottom: 20, fontFamily: 'system-ui,sans-serif' },
  mPlayer: { fontSize: 12, color: '#00a676', fontFamily: 'system-ui,sans-serif', letterSpacing: '.08em', marginBottom: 12, fontWeight: 800 },
  newSeason: { background: '#f3fbf8', color: '#246555', padding: 12, borderRadius: 8, textAlign: 'center', fontSize: 12, fontWeight: 900, letterSpacing: '.08em', marginBottom: 16, fontFamily: 'system-ui,sans-serif', border: '1px solid #cfeee3' },
  deadlineTimer: { background: '#172026', color: '#ffffff', padding: 12, borderRadius: 8, textAlign: 'center', fontSize: 18, fontWeight: 950, letterSpacing: '.08em', marginBottom: 10, fontFamily: 'system-ui,sans-serif', boxShadow: '0 14px 30px rgba(15,23,32,.16)' },
  recapCard: { background: '#ffffff', border: '1px solid #e5eaf0', borderRadius: 8, padding: 14, marginBottom: 16, boxShadow: '0 12px 28px rgba(15,23,32,.07)' },
  recapGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8, color: '#172026', fontFamily: 'system-ui,sans-serif' },
  recapItem: { background: '#f7f9fb', border: '1px solid #e5eaf0', borderRadius: 8, padding: 10 },
  resHero: { background: '#f7f9fb', border: '1px solid #e5eaf0', borderRadius: 8, padding: 20, textAlign: 'center', marginBottom: 16 },
  resLabel: { fontSize: 10, letterSpacing: '.18em', color: '#64727d', fontFamily: 'system-ui,sans-serif', marginBottom: 6, fontWeight: 850 },
  resNet: { fontSize: 36, fontWeight: 950, lineHeight: 1, marginBottom: 14 },
  resBreak: { display: 'flex', flexDirection: 'column', gap: 4, fontSize: 12, color: '#3f5663', fontFamily: 'system-ui,sans-serif' },
  evRow: { background: '#f7f9fb', padding: '10px 12px', marginBottom: 6, borderRadius: '0 8px 8px 0' },
  evPlayer: { fontSize: 12, color: '#172026', fontWeight: 850, marginBottom: 2 },
  evLabel: { fontSize: 11, color: '#3f5663', fontFamily: 'system-ui,sans-serif' },
  leavingCard: { background: '#2a1a1a', border: '1px solid #4a2a2a', borderRadius: 6, padding: 12, marginBottom: 16 },
  leavingRow: { fontSize: 12, color: '#b42318', fontFamily: 'system-ui,sans-serif', padding: '4px 0' },
  choiceList: { display: 'flex', flexDirection: 'column', gap: 8 },
  swipeHint: { background: '#f7f9fb', border: '1px solid #e5eaf0', borderRadius: 8, padding: 10, color: '#64727d', fontSize: 11, fontFamily: 'system-ui,sans-serif', marginBottom: 12 },
  choiceBtn: { background: '#ffffff', border: '1px solid #e5eaf0', borderRadius: 8, padding: '12px 14px', cursor: 'pointer', textAlign: 'left', color: '#172026', display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 10, fontFamily: 'inherit', boxShadow: '0 8px 20px rgba(15,23,32,.06)' },
  chLabel: { fontSize: 13, fontWeight: 850, marginBottom: 3, color: '#172026' },
  chDesc: { fontSize: 10, color: '#64727d', fontFamily: 'system-ui,sans-serif' },
  chCost: { fontSize: 11, color: '#b42318', fontFamily: 'system-ui,sans-serif', fontWeight: 700 },
  negoStats: { display: 'flex', flexDirection: 'column', gap: 10, marginBottom: 14 },
  negoStat: { background: '#f7f9fb', border: '1px solid #e5eaf0', borderRadius: 8, padding: 10 },
  nsLabel: { fontSize: 9, letterSpacing: '.16em', color: '#64727d', fontFamily: 'system-ui,sans-serif', fontWeight: 850, marginBottom: 4 },
  nsVal: { fontSize: 12, color: '#172026', fontFamily: 'system-ui,sans-serif', fontWeight: 850, textAlign: 'right', marginTop: 4 },
  nsPrice: { fontSize: 20, color: '#172026', fontWeight: 900 },
  logBox: { background: '#f7f9fb', border: '1px solid #e5eaf0', borderRadius: 8, padding: 10, marginBottom: 14, minHeight: 60 },
  logRow: { fontSize: 11, fontFamily: 'system-ui,sans-serif', padding: '2px 0' },
  toast: { position: 'fixed', bottom: 82, left: 20, right: 20, padding: '12px 16px', borderRadius: 8, color: '#ffffff', border: '1px solid', textAlign: 'center', fontSize: 13, fontFamily: 'system-ui,sans-serif', fontWeight: 800, animation: 'slideUp .2s ease-out', zIndex: 200, boxShadow: '0 18px 38px rgba(15,23,32,.18)' },
  navBadge: { marginLeft: 4, minWidth: 16, height: 16, borderRadius: 8, background: '#b42318', color: '#ffffff', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', fontSize: 9, fontWeight: 900 },
};
